[build]
  publish = "dist/pickLatam"
  command = "ng build"
  functions = "./src/assets/pick-functions"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [build.environment]
  NODE_VERSION="16.8.0"